const turnos=[
    {id:0, dia:'Lunes', fecha: '10/06', horario: '10.00', especialidad: 'Psiquiatra', especialista: 'Dr. Suarez', precio: 12000, img: '', value: false},
    {id:1, dia:'Lunes', fecha: '17/06', horario: '11.00', especialidad: 'Admision', especialista: 'Lic. Giachino', precio: 10000, img: ''},
    {id:2, dia:'Lunes', fecha: '17/06', horario: '12.00', especialidad: 'Admision', especialista: 'Lic. Vazquez ', precio: 10000, img: ''},
    {id:3, dia:'Lunes', fecha: '17/06', horario: '13.30', especialidad: 'Psicologia', especialista: 'Lic. Bianchi', precio: 8000, img: ''},
    {id:6, dia:'Lunes', fecha: '10/06', horario: '16.00', especialidad: 'Nutricionista', especialista: 'Lic. Storni', precio: 7500, img: ''},
    {id:7, dia:'Martes', fecha: '18/06', horario: '10.30', especialidad: 'Psiquiatra', especialista: 'Dr. Locatelli', precio: 12000, img: ''},
    {id:8, dia:'Martes', fecha: '25/06', horario: '11.00', especialidad: 'Psicologia', especialista: 'Lic. Higa', precio: 8000, img: ''},
    {id:9, dia:'Martes', fecha: '18/06', horario: '12.45', especialidad: 'Nutricionista', especialista: 'Lic. Storni', precio: 7500, img: ''},
    {id:10, dia:'Martes', fecha: '18/06', horario: '14.00', especialidad: 'Psicologia', especialista: 'Lic. Vazquez', precio: 8000, img: ''},
    {id:11, dia:'Martes', fecha: '25/06', horario: '15.00', especialidad: 'Psiquiatra', especialista: 'Dr. Suarez', precio: 12000, img: ''},
    {id:12, dia:'Miercoles', fecha: '12/06', horario: '10.00', especialidad: 'Psiquiatra', especialista: 'Dr. Locatelli', precio: 12000, img: ''},
    {id:13, dia:'Miercoles', fecha: '26/06', horario: '10.30', especialidad: 'Psicologia', especialista: 'Lic. Sisti', precio: 8000, img: ''},
    {id:14, dia:'Miercoles', fecha: '26/06', horario: '12.00', especialidad: 'Psicologia', especialista: 'Lic. Gabutti', precio: 8000, img: ''},
    {id:15, dia:'Miercoles', fecha: '03/07', horario: '14.30', especialidad: 'Nutricionista', especialista: 'Lic. Storni', precio: 7500, img: ''},
    {id:16, dia:'Jueves', fecha: '20/06', horario: '10.00', especialidad: 'Musicoterapia', especialista: 'Lic. Bellani', precio: 7500, img: ''},
    {id:17, dia:'Jueves', fecha: '04/07', horario: '10.30', especialidad: 'Psicologia', especialista: 'Lic. Bel', precio: 8000, img: ''},
    {id:18, dia:'Jueves', fecha: '04/07', horario: '11.30', especialidad: 'Psiquiatra', especialista: 'Dr. Locatelli', precio: 12000, img: ''},
    {id:19, dia:'Jueves', fecha: '27/06', horario: '16.00', especialidad: 'Psicologia', especialista: 'Lic. Donghi', precio: 8000, img: ''},
    {id:20, dia:'Jueves', fecha: '27/06', horario: '17.00', especialidad: 'Nutricionista', especialista: 'Lic. Bianchi', precio: 7500, img: ''},
    {id:21, dia:'Viernes', fecha: '28/06', horario: '11.00', especialidad: 'Psiquiatra', especialista: 'Dr. Suarez', precio: 12000, img: ''},
    {id:22, dia:'Viernes', fecha: '05/07', horario: '11.30', especialidad: 'Admision', especialista: 'Lic. Giachino', precio: 10000, img: ''},
    {id:23, dia:'Viernes', fecha: '05/07', horario: '13.45', especialidad: 'Admision', especialista: 'Lic. Giachino', precio: 10000, img: ''},
    {id:24, dia:'Viernes', fecha: '21/06', horario: '15.15', especialidad: 'Psiquiatra', especialista: 'Dr. Suarez', precio: 12000, img: ''} 
] 